# User config
author: "Dmitry Ilin"
tagline: ""
description: "Hello, I'm Dima! I am pursuing a Bachelor of Science in Computer Science at the University of Massachusetts, Amherst."
keywords: "Software Engineer, Student, UMASS, Amherst, Computer, Science,"
email: "dimailinemail@gmail.com"
linkedin: "www.linkedin.com/in/dima-ilin"
twitter:
github: "https://github.com/dima618"

# Site config
baseurl: "/aboutme"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
