# User config
author: "Dmitry Ilin"
tagline: ""
description: "hello! i am a bachelor of science in computer science at umass amherst. i am currently a software engineering intern at ipg photonics corp."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "dimailinemail@gmail.com"
linkedin: "www.linkedin.com/in/dima-ilin"
twitter:
github: "https://github.com/dima618"

# Site config
baseurl: "/aboutme"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
