# User config
author: "Dmitry Ilin"
tagline: "computer science major at umass amherst."
description: ""
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "dimailinemail@gmail.com"
linkedin: "www.linkedin.com/in/dima-ilin"
twitter:
github: "https://github.com/dima618"

# Site config
baseurl: "/aboutme"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
