# User config
author: "Dmitry Ilin"
tagline: ""
description: "Hello, I'm Dima! I am pursuing a Bachelor of Science in Computer Science at the University of Massachusetts, Amherst."
position: "Software Engineering Intern"
company: "IPG&nbsp;Photonics"
companysite: "https://www.ipgphotonics.com/en"
keywords: "Software Engineer, Student, UMASS, Amherst, Computer, Science,"
email: "dimailinemail@gmail.com"
linkedin: "https://linkedin.com/in/dima-ilin"
github: "https://github.com/dima618"

# Site config
baseurl: "aboutme"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
